### PR TITLE
added dwm_wpa.sh

### PR DESCRIPTION
**Pull request by LuchianMihai**

### CODE REVIEW

**Comment by joestandring** [comment]
Will test this out when I get home. Just a heads up, I'd prefer if ```#/bin/sh``` was used instead of ```#!/bin/mksh``` for portability. Looks like a great addition otherwise :)

**Comment by LuchianMihai** [comment]
> Will test this out when I get home. Just a heads up, I'd prefer if `#/bin/sh` was used instead of `#!/bin/mksh` for portability. Looks like a great addition otherwise :)

Well, as I think you know, `/bin/sh` si just a simlink to whatever shell you choose (by default bash). My `/bin/sh` is a simlink to `/usr/bin/dash` (a posix compliant shell), so I do not think it knows how to print unicode, but I cannot say I have tested that. Will try that when I get home.

**Comment by joestandring** [comment]
Thanks, I'm also not able to test wpa as I'm using a wired connection. Could you get a screenshot/paste of the output if it works?

**Comment by LuchianMihai** [comment]
2020-02-07-203436_1366x768_scrot
2020-02-07-203527_1366x768_scrot
2020-02-07-203530_1366x768_scrot
2020-02-07-203538_1366x768_scrot

As requested, thou not all states covered in screenshots

**Comment by joestandring** [comment]
Thank you, I'm happy to merge this now. :)

**Pull request merged**
